package hr.krunoslav.magazin.sfshop.jaxb.elements;

//

//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2017.04.16 at 09:10:33 PM CEST 
//

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
* &lt;complexType>
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;sequence>
*         &lt;element name="template">
*           &lt;complexType>
*             &lt;complexContent>
*               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*                 &lt;sequence>
*                   &lt;element name="field">
*                     &lt;complexType>
*                       &lt;complexContent>
*                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*                           &lt;attribute name="idx" type="{http://www.w3.org/2001/XMLSchema}int" />
*                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
*                           &lt;attribute name="descr" type="{http://www.w3.org/2001/XMLSchema}string" />
*                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
*                           &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
*                           &lt;attribute name="access" type="{http://www.w3.org/2001/XMLSchema}string" />
*                           &lt;attribute name="content" type="{http://www.w3.org/2001/XMLSchema}string" />
*                         &lt;/restriction>
*                       &lt;/complexContent>
*                     &lt;/complexType>
*                   &lt;/element>
*                 &lt;/sequence>
*               &lt;/restriction>
*             &lt;/complexContent>
*           &lt;/complexType>
*         &lt;/element>
*         &lt;element name="items">
*           &lt;complexType>
*             &lt;complexContent>
*               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*                 &lt;sequence>
*                   &lt;element name="item">
*                     &lt;complexType>
*                       &lt;complexContent>
*                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*                           &lt;sequence>
*                             &lt;element name="value0" type="{http://www.w3.org/2001/XMLSchema}int"/>
*                             &lt;element name="value2">
*                               &lt;complexType>
*                                 &lt;complexContent>
*                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*                                     &lt;attribute name="min" type="{http://www.w3.org/2001/XMLSchema}string" />
*                                     &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}string" />
*                                   &lt;/restriction>
*                                 &lt;/complexContent>
*                               &lt;/complexType>
*                             &lt;/element>
*                             &lt;element name="value5" type="{http://www.w3.org/2001/XMLSchema}int"/>
*                             &lt;element name="value6" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
*                             &lt;element name="value7" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
*                             &lt;element name="value8" type="{http://www.w3.org/2001/XMLSchema}string"/>
*                             &lt;element name="value9" type="{http://www.w3.org/2001/XMLSchema}int"/>
*                           &lt;/sequence>
*                           &lt;attribute name="uid" type="{http://www.w3.org/2001/XMLSchema}int" />
*                         &lt;/restriction>
*                       &lt;/complexContent>
*                     &lt;/complexType>
*                   &lt;/element>
*                 &lt;/sequence>
*               &lt;/restriction>
*             &lt;/complexContent>
*           &lt;/complexType>
*         &lt;/element>
*       &lt;/sequence>
*       &lt;attribute name="timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "template", "items" })
@XmlRootElement(name = "inventory")
public class Inventory {

	
	@Override
	public String toString() {
		return "Inventory [timestamp=" + timestamp + ", template=" + template + ", items=" + items + "]";
	}


	@XmlAttribute(name = "timestamp")
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar timestamp;
	
	@XmlElement(required = true)
	protected Template template;
	
	@XmlElement(required = true)
	protected Items items;



	public Template getTemplate() {
		return template;
	}


	public void setTemplate(Template value) {
		this.template = value;
	}


	public Items getItems() {
		return items;
	}


	public void setItems(Items value) {
		this.items = value;
	}


	public XMLGregorianCalendar getTimestamp() {
		return timestamp;
	}


	public void setTimestamp(XMLGregorianCalendar value) {
		this.timestamp = value;
	}

}
