//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.16 at 11:10:03 PM CEST 
//

@XmlSchema(namespace = "com:tecit:inventory:02:02", elementFormDefault = XmlNsForm.QUALIFIED)
package hr.krunoslav.magazin.sfshop.jaxb.elements;

import javax.xml.bind.annotation.XmlSchema;
import javax.xml.bind.annotation.XmlNsForm;
